// Command gendocs renders the rule reference under docs/reference/rules/ from
// the check descriptors in internal/checks/registry.go, and the inspector
// reference under docs/reference/inspectors/ from internal/inspect/registry.go.
// Run via `make docs-gen`. CI fails if the working tree drifts from its output,
// so the registries are the single source of truth for that documentation.
package main

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/katabase-ai/katalyst/internal/checks"
	"github.com/katabase-ai/katalyst/internal/inspect"
)

// outDir is the generated rules section, relative to the repo root.
const outDir = "docs/content/reference/rules"

// inspectorsOut is the generated inspectors section, relative to the repo root.
const inspectorsOut = "docs/content/reference/inspectors"

func main() {
	if err := run(); err != nil {
		fmt.Fprintln(os.Stderr, "gendocs:", err)
		os.Exit(1)
	}
}

func run() error {
	// Remove the existing generated tree so deletions propagate, then
	// rewrite it from scratch.
	if err := os.RemoveAll(outDir); err != nil {
		return err
	}

	families := checks.Families()
	byFamily := map[string][]checks.Descriptor{}
	for _, d := range checks.Descriptors() {
		byFamily[d.Family] = append(byFamily[d.Family], d)
	}

	// Section landing page.
	if err := write(filepath.Join(outDir, "_index.md"), sectionIndex(families, byFamily)); err != nil {
		return err
	}

	for fi, fam := range families {
		dir := filepath.Join(outDir, fam.ID)
		ds := byFamily[fam.ID]
		// Family landing page; weight orders families within the section.
		if err := write(filepath.Join(dir, "_index.md"), familyIndex(fam, ds, (fi+1)*10)); err != nil {
			return err
		}
		for di, d := range ds {
			if err := write(filepath.Join(dir, d.Slug+".md"), rulePage(d, (di+1)*10)); err != nil {
				return err
			}
		}
	}

	// Inspectors reference: a single index page grouped by family. Inspectors
	// have no config surface, so they need no per-inspector pages.
	if err := os.RemoveAll(inspectorsOut); err != nil {
		return err
	}
	return write(filepath.Join(inspectorsOut, "_index.md"), inspectorsIndex())
}

func inspectorsIndex() string {
	byFamily := map[string][]inspect.Descriptor{}
	for _, d := range inspect.Descriptors() {
		byFamily[d.Family] = append(byFamily[d.Family], d)
	}
	var b strings.Builder
	fmt.Fprint(&b, "+++\ntitle = \"Inspectors\"\nweight = 45\n+++\n\n")
	fmt.Fprintln(&b, "<!-- GENERATED by cmd/gendocs from internal/inspect/registry.go. Do not edit by hand; run `make docs-gen`. -->")
	fmt.Fprint(&b, "\n# Inspectors reference\n\n")
	fmt.Fprint(&b, "Inspectors describe the shape of a markdown corpus and return evidence — ")
	fmt.Fprint(&b, "counts and distributions, never recommendations. They are the descriptive ")
	fmt.Fprint(&b, "dual of [rules]({{< relref \"../rules/_index.md\" >}}) and drive the ")
	fmt.Fprint(&b, "[`inspect`]({{< relref \"commands.md\" >}}) command. This page is generated ")
	fmt.Fprint(&b, "from the inspector registry, so it always matches the shipped engine.\n")
	for _, fam := range inspect.Families() {
		ds := byFamily[fam.ID]
		if len(ds) == 0 {
			continue
		}
		fmt.Fprintf(&b, "\n## %s\n\n%s\n\n", fam.Title, fam.Intro)
		for _, d := range ds {
			fmt.Fprintf(&b, "- `%s` — %s\n", d.Name, plain(d.Summary))
		}
	}
	return b.String()
}

const generatedNote = "<!-- GENERATED by cmd/gendocs from internal/checks/registry.go. Do not edit by hand; run `make docs-gen`. -->"

func sectionIndex(families []checks.Family, byFamily map[string][]checks.Descriptor) string {
	var b strings.Builder
	fmt.Fprint(&b, "+++\ntitle = \"Rules\"\nweight = 40\nbookCollapseSection = true\n+++\n\n")
	fmt.Fprintln(&b, generatedNote)
	fmt.Fprint(&b, "\n# Rules reference\n\n")
	fmt.Fprint(&b, "The checks `katalyst` runs against each item, grouped by family. ")
	fmt.Fprint(&b, "These pages are generated from the checks registry, so they always match the shipped engine.\n")
	for _, fam := range families {
		fmt.Fprintf(&b, "\n## %s\n\n%s\n\n", fam.Title, fam.Intro)
		for _, d := range byFamily[fam.ID] {
			fmt.Fprintf(&b, "- [%s]({{< relref \"%s/%s.md\" >}}) — %s\n", d.Title, fam.ID, d.Slug, plain(d.Summary))
		}
	}
	return b.String()
}

func familyIndex(fam checks.Family, ds []checks.Descriptor, weight int) string {
	var b strings.Builder
	fmt.Fprintf(&b, "+++\ntitle = \"%s\"\nweight = %d\nbookCollapseSection = true\n+++\n\n", fam.Title, weight)
	fmt.Fprintln(&b, generatedNote)
	fmt.Fprintf(&b, "\n%s\n\n", fam.Intro)
	fmt.Fprint(&b, "Checks in this family:\n\n")
	for _, d := range ds {
		fmt.Fprintf(&b, "- [%s]({{< relref \"%s.md\" >}}) — %s\n", d.Title, d.Slug, plain(d.Summary))
	}
	return b.String()
}

func rulePage(d checks.Descriptor, weight int) string {
	var b strings.Builder
	fmt.Fprintf(&b, "+++\ntitle = \"%s\"\nweight = %d\n+++\n\n", d.Title, weight)
	fmt.Fprintln(&b, generatedNote)
	fmt.Fprintf(&b, "\n## Rule ID\n\n`kind: %s`\n\n", d.Kind)
	fmt.Fprintf(&b, "## Purpose\n\n%s\n\n", d.Summary)
	if len(d.Fields) > 0 {
		fmt.Fprint(&b, "## Configuration keys\n\n")
		fmt.Fprint(&b, "| Field | Required | Default | Meaning |\n|---|---|---|---|\n")
		for _, f := range d.Fields {
			req := "no"
			if f.Required {
				req = "yes"
			}
			def := f.Default
			if def == "" {
				def = "—"
			} else {
				def = "`" + def + "`"
			}
			fmt.Fprintf(&b, "| `%s` | %s | %s | %s |\n", f.Name, req, def, f.Desc)
		}
		fmt.Fprintln(&b)
	}
	fmt.Fprintf(&b, "## Example\n\n```yaml\n%s\n```\n", d.ConfigExample)
	return b.String()
}

// plain strips inline-code backticks from a summary so it reads cleanly in a
// link list.
func plain(s string) string {
	return strings.ReplaceAll(s, "`", "")
}

// write creates parent directories and writes content with a trailing
// newline normalized.
func write(path, content string) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	out := []byte(content)
	if !bytes.HasSuffix(out, []byte("\n")) {
		out = append(out, '\n')
	}
	return os.WriteFile(path, out, 0o644)
}
